### ISSUE TITLE
Reduce the number of concurrent requests

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#212]
Determine if the large number of concurrent requests (50) is really necessary.  

### Tasks
- [ ] Validate Initial download speeds are not affected
	- [ ] Dota 2 (570)
	- [ ] Have user with gigabit+ internet test download speeds
- [ ] Validate fully cached download speeds are no affected
	- [ ] Dota 2
- [ ] Check to see that internet speeds are generally unaffected

**Comment by tpill90** [comment]
Released in [v1.8.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.8.0)
