### ISSUE TITLE
Upgrade to dotnet 7

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#215]
## Tasks

- [ ] Update csproj to reference dotnet 7
- [ ] Regression test performance
	- [ ] CPU Usage
	- [ ] Memory
	- [ ] Throughput
- [ ] Validate app trimming still works https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/7.0/trim-all-assemblies
- [ ] Compare compiled binary size between dotnet 6 and 7

**Comment by tpill90** [comment]
I'm seeing a large increase in CPU consumption by upgrading to dotnet7, however throughput is nearly the same as using dotnet 6

### dotnet6 CPU
![image](https://user-images.githubusercontent.com/766513/201542600-05a178c6-7ffe-4cb4-b7fc-b1df3ca1a48a.png)

### dotnet7 CPU
![image](https://user-images.githubusercontent.com/766513/201542627-12129b8d-62db-4c51-bac7-09cbea232562.png)

**Comment by tpill90** [comment]
Potentially related issue https://github.com/dotnet/runtime/issues/78127

**Comment by AndyAyersMS** [comment]
@tpill90 curious if you ever tracked this one down.

The issue you noted above looks to be fixed in .NET 8 (the fix will first show up in Preview 4, likely available sometime in May). But the change you noticed may be caused by something else.

**Comment by tpill90** [comment]
@AndyAyersMS 

I haven't looked at this recently, not since I initially made this issue.  I did some profiling then with both Visual Studio and dotTrace, but wasn't able to find anything obvious in my code that seemed to be the issue.  There certainly was an increase in resource consumption, but I couldn't tell where it was my code versus the framework.

I'll come back around to this in May and see if anything changes.  I'll let you know the results either way.  Thanks for checking in!

**Comment by tpill90** [comment]
@AndyAyersMS Looks like this is no longer an issue in .NET 8.  Tested on both .NET 6 and .NET 8 and they have the same throughput and CPU consumption.
